
export const metadata = {
    title: "Tourist Places",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <main>
            {children}
        </main>
    );
}
