import "./globals.css";
import 'swiper/css';

export const metadata = {
  title: "Deadpool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
