/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function RomeColosseum(props) {
  const { nodes, materials } = useGLTF('/models/rome_colosseum.glb')
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        castShadow={false}
        receiveShadow={false}
        geometry={nodes.Model_material0_0.geometry}
        material={materials.material0}
        rotation={[-0.369, -0.263, -0.006]}
      />
    </group>
  )
}

useGLTF.preload('/models/rome_colosseum.glb')
